[project]
name = "task-6-bayt-al-hikma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mysql-connector-python>=9.2.0",
    "streamlit>=1.43.2",
    "tabulate>=0.9.0",
]
